apiVersion: v1
kind: Service
metadata:
  name: demo-application
  namespace: {{ .Values.NAMESPACE  }}
  labels:
    app: demo-application
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: demo-application